server:
  port: 9616

spring:
  application:
    name: potic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/rbac?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
    password: zhouzuyi.com
    username: root
#  redis:
#    host: 127.0.0.1
#    port: 6399
#    password: null
#    database: 0
#    timeout: 60000
#    lettuce:
#      shutdown-timeout: 100
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）,默认值8
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制,单位毫秒）,默认值-1
#        max-wait: -1
#        # 连接池中的最大空闲连接,默认值8
#        max-idle: 8
#        # 连接池中的最小空闲连接,默认值0
#        min-idle: 0